# 基础路径配置
paths:
  log_path: "logs"
  checkpoint_path: "checkpoints"

# log 策略
log_freq: 5
checkpoint_freq: 50

hyper_parameters:
  # 环境配置
  framework: torch

  # 核心DQN参数
  lr: 6.25e-05
  gamma: 0.99
  double_q: true
  dueling: false
  n_step: 1
  noisy: false
  num_atoms: 1

  # 网络架构
  hiddens: [ 512 ]

  # Adam优化器
  adam_epsilon: 0.00015

  # 目标网络更新
  target_network_update_freq: 10000

  # 学习调度
  num_steps_sampled_before_learning_starts: 20000
  min_sample_timesteps_per_iteration: 5000

  # 探索参数
  final_epsilon: 0.01
  epsilon_timesteps: 1000000

  # 训练批次配置
  train_batch_size: 32
  rollout_fragment_length: 4

  # 资源配置
  num_gpus: 1
  num_cpus: 10
  num_envs_per_worker: 20
  num_gpus_per_worker: 0.01
  num_cpus_per_worker: 2

  optimizer:
    num_replay_buffer_shards: 1
    async_replay_optimizer: True


