# Inherit base configuration
extends: templates/apex_base.yml

hyper_parameters:
  replay_buffer_config:
    capacity: 1000000
    prioritized_replay_alpha: 0.5
    prioritized_replay_beta: 1.0
    prioritized_replay_eps: 0.000001
    type: MultiAgentPrioritizedReplayBuffer
    replay_buffer_shards_colocated_with_driver: true
    worker_side_prioritization: true
    no_local_replay_buffer: true

run_config:
  use_mlflow: true
  run_name_template: "{env_in}_APEX_PER"
  max_iterations: 200
  max_time_s: 18000  # 5 hours