extends: templates/apex_base.yml

hyper_parameters:
  # Training batch - APEX directly samples this many blocks from buffer
  # With sub_buffer_size=16, this means 512 transitions per batch
  train_batch_size: 32
  
  # Replay buffer (RASPBERry)
  replay_buffer_config:
    capacity: 100000
    prioritized_replay_alpha: 0.5
    prioritized_replay_beta: 1.0
    prioritized_replay_eps: 0.000001
    type: MultiAgentRASPBERryReplayBuffer
    sub_buffer_size: 16
    compress_base: -1
    replay_buffer_shards_colocated_with_driver: true
    worker_side_prioritization: true
    no_local_replay_buffer: true
    compress_pool_size: 200
    compression_algorithm: "lz4"
    compression_level: 1
    compression_nthreads: 10
    compression_mode: "D"             # 改为批量异步模式，与单机版本一致
    chunk_size: 20

run_config:
  use_mlflow: true
  run_name_template: "{env_in}_APEX_RASPBERRY"
  max_iterations: 500
  max_time_s: 7200
