# Inherit base configuration
extends: templates/ddqn_base.yml

hyper_parameters:
  replay_buffer_config:
    capacity: 1000000
    prioritized_replay_alpha: 0.5
    prioritized_replay_beta: 1.0
    prioritized_replay_eps: 0.000001
    type: MultiAgentPrioritizedReplayBuffer
  # Override resources for concurrent 3h compare run
  num_cpus: 4
  num_gpus: 1
