# 继承基础配置
extends: templates/sac_base.yml

hyper_parameters:
  replay_buffer_config:
    capacity: 500000
    prioritized_replay_alpha: 0.5
    prioritized_replay_beta: 1
    prioritized_replay_eps: 0.000001
    type: MultiAgentPrioritizedReplayBuffer