# SAC-RASPBERry configuration for VECTOR observation environments
# (LunarLanderContinuous, BipedalWalker)
extends: templates/sac_vector_base.yml

hyper_parameters:
  training_intensity: 1.0
  replay_buffer_config:
    capacity: 1000000
    prioritized_replay_alpha: 0.5
    prioritized_replay_beta: 1.0
    prioritized_replay_eps: 0.000001
    type: MultiAgentRASPBERryReplayBuffer
    sub_buffer_size: 16
    compress_base: -1
    worker_side_prioritization: true
    compress_pool_size: 400
    num_ray_workers: 4
    max_inflight_tasks: 16
    compression_algorithm: "lz4"
    compression_level: 1
    compression_nthreads: 4
    compression_mode: "C"
    chunk_size: 20

