# 继承基础配置
extends: templates/sac_base.yml

hyper_parameters:
  replay_buffer_config:
    capacity: 100000
    prioritized_replay_alpha: 0.5
    prioritized_replay_beta: 0.4
    block_size: 8                        # RASPBERry特有参数
    compress_base: -1                    # 自动压缩维度选择
    split_mini_batch: 4                  # 小批量分割
    num_save: 100                        # 保持未压缩的块数
    store: 2000                          # 存储管理参数
    type: MultiAgentPrioritizedBlockReplayBuffer